<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('all_country_pincodes')->delete();

		$countries = array(
			array('postal_code' => 'US', 'country' => 'United States'),
			array('postal_code' => 'CA', 'country' => 'Canada'),
			array('postal_code' => 'AF', 'country' => 'Afghanistan'),
			array('postal_code' => 'AL', 'country' => 'Albania'),
			array('postal_code' => 'DZ', 'country' => 'Algeria'),
			array('postal_code' => 'AS', 'country' => 'American Samoa'),
			array('postal_code' => 'AD', 'country' => 'Andorra'),
			array('postal_code' => 'AO', 'country' => 'Angola'),
			array('postal_code' => 'AI', 'country' => 'Anguilla'),
			array('postal_code' => 'AQ', 'country' => 'Antarctica'),
			array('postal_code' => 'AG', 'country' => 'Antigua and/or Barbuda'),
			array('postal_code' => 'AR', 'country' => 'Argentina'),
			array('postal_code' => 'AM', 'country' => 'Armenia'),
			array('postal_code' => 'AW', 'country' => 'Aruba'),
			array('postal_code' => 'AU', 'country' => 'Australia'),
			array('postal_code' => 'AT', 'country' => 'Austria'),
			array('postal_code' => 'AZ', 'country' => 'Azerbaijan'),
			array('postal_code' => 'BS', 'country' => 'Bahamas'),
			array('postal_code' => 'BH', 'country' => 'Bahrain'),
			array('postal_code' => 'BD', 'country' => 'Bangladesh'),
			array('postal_code' => 'BB', 'country' => 'Barbados'),
			array('postal_code' => 'BY', 'country' => 'Belarus'),
			array('postal_code' => 'BE', 'country' => 'Belgium'),
			array('postal_code' => 'BZ', 'country' => 'Belize'),
			array('postal_code' => 'BJ', 'country' => 'Benin'),
			array('postal_code' => 'BM', 'country' => 'Bermuda'),
			array('postal_code' => 'BT', 'country' => 'Bhutan'),
			array('postal_code' => 'BO', 'country' => 'Bolivia'),
			array('postal_code' => 'BA', 'country' => 'Bosnia and Herzegovina'),
			array('postal_code' => 'BW', 'country' => 'Botswana'),
			array('postal_code' => 'BV', 'country' => 'Bouvet Island'),
			array('postal_code' => 'BR', 'country' => 'Brazil'),
			array('postal_code' => 'IO', 'country' => 'British lndian Ocean Territory'),
			array('postal_code' => 'BN', 'country' => 'Brunei Darussalam'),
			array('postal_code' => 'BG', 'country' => 'Bulgaria'),
			array('postal_code' => 'BF', 'country' => 'Burkina Faso'),
			array('postal_code' => 'BI', 'country' => 'Burundi'),
			array('postal_code' => 'KH', 'country' => 'Cambodia'),
			array('postal_code' => 'CM', 'country' => 'Cameroon'),
			array('postal_code' => 'CV', 'country' => 'Cape Verde'),
			array('postal_code' => 'KY', 'country' => 'Cayman Islands'),
			array('postal_code' => 'CF', 'country' => 'Central African Republic'),
			array('postal_code' => 'TD', 'country' => 'Chad'),
			array('postal_code' => 'CL', 'country' => 'Chile'),
			array('postal_code' => 'CN', 'country' => 'China'),
			array('postal_code' => 'CX', 'country' => 'Christmas Island'),
			array('postal_code' => 'CC', 'country' => 'Cocos (Keeling) Islands'),
			array('postal_code' => 'CO', 'country' => 'Colombia'),
			array('postal_code' => 'KM', 'country' => 'Comoros'),
			array('postal_code' => 'CG', 'country' => 'Congo'),
			array('postal_code' => 'CK', 'country' => 'Cook Islands'),
			array('postal_code' => 'CR', 'country' => 'Costa Rica'),
			array('postal_code' => 'HR', 'country' => 'Croatia (Hrvatska)'),
			array('postal_code' => 'CU', 'country' => 'Cuba'),
			array('postal_code' => 'CY', 'country' => 'Cyprus'),
			array('postal_code' => 'CZ', 'country' => 'Czech Republic'),
			array('postal_code' => 'CD', 'country' => 'Democratic Republic of Congo'),
			array('postal_code' => 'DK', 'country' => 'Denmark'),
			array('postal_code' => 'DJ', 'country' => 'Djibouti'),
			array('postal_code' => 'DM', 'country' => 'Dominica'),
			array('postal_code' => 'DO', 'country' => 'Dominican Republic'),
			array('postal_code' => 'TP', 'country' => 'East Timor'),
			array('postal_code' => 'EC', 'country' => 'Ecudaor'),
			array('postal_code' => 'EG', 'country' => 'Egypt'),
			array('postal_code' => 'SV', 'country' => 'El Salvador'),
			array('postal_code' => 'GQ', 'country' => 'Equatorial Guinea'),
			array('postal_code' => 'ER', 'country' => 'Eritrea'),
			array('postal_code' => 'EE', 'country' => 'Estonia'),
			array('postal_code' => 'ET', 'country' => 'Ethiopia'),
			array('postal_code' => 'FK', 'country' => 'Falkland Islands (Malvinas)'),
			array('postal_code' => 'FO', 'country' => 'Faroe Islands'),
			array('postal_code' => 'FJ', 'country' => 'Fiji'),
			array('postal_code' => 'FI', 'country' => 'Finland'),
			array('postal_code' => 'FR', 'country' => 'France'),
			array('postal_code' => 'FX', 'country' => 'France, Metropolitan'),
			array('postal_code' => 'GF', 'country' => 'French Guiana'),
			array('postal_code' => 'PF', 'country' => 'French Polynesia'),
			array('postal_code' => 'TF', 'country' => 'French Southern Territories'),
			array('postal_code' => 'GA', 'country' => 'Gabon'),
			array('postal_code' => 'GM', 'country' => 'Gambia'),
			array('postal_code' => 'GE', 'country' => 'Georgia'),
			array('postal_code' => 'DE', 'country' => 'Germany'),
			array('postal_code' => 'GH', 'country' => 'Ghana'),
			array('postal_code' => 'GI', 'country' => 'Gibraltar'),
			array('postal_code' => 'GR', 'country' => 'Greece'),
			array('postal_code' => 'GL', 'country' => 'Greenland'),
			array('postal_code' => 'GD', 'country' => 'Grenada'),
			array('postal_code' => 'GP', 'country' => 'Guadeloupe'),
			array('postal_code' => 'GU', 'country' => 'Guam'),
			array('postal_code' => 'GT', 'country' => 'Guatemala'),
			array('postal_code' => 'GN', 'country' => 'Guinea'),
			array('postal_code' => 'GW', 'country' => 'Guinea-Bissau'),
			array('postal_code' => 'GY', 'country' => 'Guyana'),
			array('postal_code' => 'HT', 'country' => 'Haiti'),
			array('postal_code' => 'HM', 'country' => 'Heard and Mc Donald Islands'),
			array('postal_code' => 'HN', 'country' => 'Honduras'),
			array('postal_code' => 'HK', 'country' => 'Hong Kong'),
			array('postal_code' => 'HU', 'country' => 'Hungary'),
			array('postal_code' => 'IS', 'country' => 'Iceland'),
			array('postal_code' => 'IN', 'country' => 'India'),
			array('postal_code' => 'ID', 'country' => 'Indonesia'),
			array('postal_code' => 'IR', 'country' => 'Iran (Islamic Republic of)'),
			array('postal_code' => 'IQ', 'country' => 'Iraq'),
			array('postal_code' => 'IE', 'country' => 'Ireland'),
			array('postal_code' => 'IL', 'country' => 'Israel'),
			array('postal_code' => 'IT', 'country' => 'Italy'),
			array('postal_code' => 'CI', 'country' => 'Ivory Coast'),
			array('postal_code' => 'JM', 'country' => 'Jamaica'),
			array('postal_code' => 'JP', 'country' => 'Japan'),
			array('postal_code' => 'JO', 'country' => 'Jordan'),
			array('postal_code' => 'KZ', 'country' => 'Kazakhstan'),
			array('postal_code' => 'KE', 'country' => 'Kenya'),
			array('postal_code' => 'KI', 'country' => 'Kiribati'),
			array('postal_code' => 'KP', 'country' => 'Korea, Democratic People\'s Republic of'),
			array('postal_code' => 'KR', 'country' => 'Korea, Republic of'),
			array('postal_code' => 'KW', 'country' => 'Kuwait'),
			array('postal_code' => 'KG', 'country' => 'Kyrgyzstan'),
			array('postal_code' => 'LA', 'country' => 'Lao People\'s Democratic Republic'),
			array('postal_code' => 'LV', 'country' => 'Latvia'),
			array('postal_code' => 'LB', 'country' => 'Lebanon'),
			array('postal_code' => 'LS', 'country' => 'Lesotho'),
			array('postal_code' => 'LR', 'country' => 'Liberia'),
			array('postal_code' => 'LY', 'country' => 'Libyan Arab Jamahiriya'),
			array('postal_code' => 'LI', 'country' => 'Liechtenstein'),
			array('postal_code' => 'LT', 'country' => 'Lithuania'),
			array('postal_code' => 'LU', 'country' => 'Luxembourg'),
			array('postal_code' => 'MO', 'country' => 'Macau'),
			array('postal_code' => 'MK', 'country' => 'Macedonia'),
			array('postal_code' => 'MG', 'country' => 'Madagascar'),
			array('postal_code' => 'MW', 'country' => 'Malawi'),
			array('postal_code' => 'MY', 'country' => 'Malaysia'),
			array('postal_code' => 'MV', 'country' => 'Maldives'),
			array('postal_code' => 'ML', 'country' => 'Mali'),
			array('postal_code' => 'MT', 'country' => 'Malta'),
			array('postal_code' => 'MH', 'country' => 'Marshall Islands'),
			array('postal_code' => 'MQ', 'country' => 'Martinique'),
			array('postal_code' => 'MR', 'country' => 'Mauritania'),
			array('postal_code' => 'MU', 'country' => 'Mauritius'),
			array('postal_code' => 'TY', 'country' => 'Mayotte'),
			array('postal_code' => 'MX', 'country' => 'Mexico'),
			array('postal_code' => 'FM', 'country' => 'Micronesia, Federated States of'),
			array('postal_code' => 'MD', 'country' => 'Moldova, Republic of'),
			array('postal_code' => 'MC', 'country' => 'Monaco'),
			array('postal_code' => 'MN', 'country' => 'Mongolia'),
			array('postal_code' => 'MS', 'country' => 'Montserrat'),
			array('postal_code' => 'MA', 'country' => 'Morocco'),
			array('postal_code' => 'MZ', 'country' => 'Mozambique'),
			array('postal_code' => 'MM', 'country' => 'Myanmar'),
			array('postal_code' => 'NA', 'country' => 'Namibia'),
			array('postal_code' => 'NR', 'country' => 'Nauru'),
			array('postal_code' => 'NP', 'country' => 'Nepal'),
			array('postal_code' => 'NL', 'country' => 'Netherlands'),
			array('postal_code' => 'AN', 'country' => 'Netherlands Antilles'),
			array('postal_code' => 'NC', 'country' => 'New Caledonia'),
			array('postal_code' => 'NZ', 'country' => 'New Zealand'),
			array('postal_code' => 'NI', 'country' => 'Nicaragua'),
			array('postal_code' => 'NE', 'country' => 'Niger'),
			array('postal_code' => 'NG', 'country' => 'Nigeria'),
			array('postal_code' => 'NU', 'country' => 'Niue'),
			array('postal_code' => 'NF', 'country' => 'Norfork Island'),
			array('postal_code' => 'MP', 'country' => 'Northern Mariana Islands'),
			array('postal_code' => 'NO', 'country' => 'Norway'),
			array('postal_code' => 'OM', 'country' => 'Oman'),
			array('postal_code' => 'PK', 'country' => 'Pakistan'),
			array('postal_code' => 'PW', 'country' => 'Palau'),
			array('postal_code' => 'PA', 'country' => 'Panama'),
			array('postal_code' => 'PG', 'country' => 'Papua New Guinea'),
			array('postal_code' => 'PY', 'country' => 'Paraguay'),
			array('postal_code' => 'PE', 'country' => 'Peru'),
			array('postal_code' => 'PH', 'country' => 'Philippines'),
			array('postal_code' => 'PN', 'country' => 'Pitcairn'),
			array('postal_code' => 'PL', 'country' => 'Poland'),
			array('postal_code' => 'PT', 'country' => 'Portugal'),
			array('postal_code' => 'PR', 'country' => 'Puerto Rico'),
			array('postal_code' => 'QA', 'country' => 'Qatar'),
			array('postal_code' => 'SS', 'country' => 'Republic of South Sudan'),
			array('postal_code' => 'RE', 'country' => 'Reunion'),
			array('postal_code' => 'RO', 'country' => 'Romania'),
			array('postal_code' => 'RU', 'country' => 'Russian Federation'),
			array('postal_code' => 'RW', 'country' => 'Rwanda'),
			array('postal_code' => 'KN', 'country' => 'Saint Kitts and Nevis'),
			array('postal_code' => 'LC', 'country' => 'Saint Lucia'),
			array('postal_code' => 'VC', 'country' => 'Saint Vincent and the Grenadines'),
			array('postal_code' => 'WS', 'country' => 'Samoa'),
			array('postal_code' => 'SM', 'country' => 'San Marino'),
			array('postal_code' => 'ST', 'country' => 'Sao Tome and Principe'),
			array('postal_code' => 'SA', 'country' => 'Saudi Arabia'),
			array('postal_code' => 'SN', 'country' => 'Senegal'),
			array('postal_code' => 'RS', 'country' => 'Serbia'),
			array('postal_code' => 'SC', 'country' => 'Seychelles'),
			array('postal_code' => 'SL', 'country' => 'Sierra Leone'),
			array('postal_code' => 'SG', 'country' => 'Singapore'),
			array('postal_code' => 'SK', 'country' => 'Slovakia'),
			array('postal_code' => 'SI', 'country' => 'Slovenia'),
			array('postal_code' => 'SB', 'country' => 'Solomon Islands'),
			array('postal_code' => 'SO', 'country' => 'Somalia'),
			array('postal_code' => 'ZA', 'country' => 'South Africa'),
			array('postal_code' => 'GS', 'country' => 'South Georgia South Sandwich Islands'),
			array('postal_code' => 'ES', 'country' => 'Spain'),
			array('postal_code' => 'LK', 'country' => 'Sri Lanka'),
			array('postal_code' => 'SH', 'country' => 'St. Helena'),
			array('postal_code' => 'PM', 'country' => 'St. Pierre and Miquelon'),
			array('postal_code' => 'SD', 'country' => 'Sudan'),
			array('postal_code' => 'SR', 'country' => 'Suricountry'),
			array('postal_code' => 'SJ', 'country' => 'Svalbarn and Jan Mayen Islands'),
			array('postal_code' => 'SZ', 'country' => 'Swaziland'),
			array('postal_code' => 'SE', 'country' => 'Sweden'),
			array('postal_code' => 'CH', 'country' => 'Switzerland'),
			array('postal_code' => 'SY', 'country' => 'Syrian Arab Republic'),
			array('postal_code' => 'TW', 'country' => 'Taiwan'),
			array('postal_code' => 'TJ', 'country' => 'Tajikistan'),
			array('postal_code' => 'TZ', 'country' => 'Tanzania, United Republic of'),
			array('postal_code' => 'TH', 'country' => 'Thailand'),
			array('postal_code' => 'TG', 'country' => 'Togo'),
			array('postal_code' => 'TK', 'country' => 'Tokelau'),
			array('postal_code' => 'TO', 'country' => 'Tonga'),
			array('postal_code' => 'TT', 'country' => 'Trinidad and Tobago'),
			array('postal_code' => 'TN', 'country' => 'Tunisia'),
			array('postal_code' => 'TR', 'country' => 'Turkey'),
			array('postal_code' => 'TM', 'country' => 'Turkmenistan'),
			array('postal_code' => 'TC', 'country' => 'Turks and Caicos Islands'),
			array('postal_code' => 'TV', 'country' => 'Tuvalu'),
			array('postal_code' => 'UG', 'country' => 'Uganda'),
			array('postal_code' => 'UA', 'country' => 'Ukraine'),
			array('postal_code' => 'AE', 'country' => 'United Arab Emirates'),
			array('postal_code' => 'GB', 'country' => 'United Kingdom'),
			array('postal_code' => 'UM', 'country' => 'United States minor outlying islands'),
			array('postal_code' => 'UY', 'country' => 'Uruguay'),
			array('postal_code' => 'UZ', 'country' => 'Uzbekistan'),
			array('postal_code' => 'VU', 'country' => 'Vanuatu'),
			array('postal_code' => 'VA', 'country' => 'Vatican City State'),
			array('postal_code' => 'VE', 'country' => 'Venezuela'),
			array('postal_code' => 'VN', 'country' => 'Vietnam'),
			array('postal_code' => 'VG', 'country' => 'Virgin Islands (British)'),
			array('postal_code' => 'VI', 'country' => 'Virgin Islands (U.S.)'),
			array('postal_code' => 'WF', 'country' => 'Wallis and Futuna Islands'),
			array('postal_code' => 'EH', 'country' => 'Western Sahara'),
			array('postal_code' => 'YE', 'country' => 'Yemen'),
			array('postal_code' => 'YU', 'country' => 'Yugoslavia'),
			array('postal_code' => 'ZR', 'country' => 'Zaire'),
			array('postal_code' => 'ZM', 'country' => 'Zambia'),
			array('postal_code' => 'ZW', 'country' => 'Zimbabwe'),
		);

		DB::table('all_country_pincodes')->insert($countries);
    }
}
